name: Release CS2 Plugin

on:
  workflow_dispatch:

env:
  PLUGIN_NAME: plugin
  SOURCE_DIR: ./src
  INSTALL_PATH: /game/csgo/addons/swiftly/

jobs:
  generate-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get latest tag and set version
        id: get_version
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.9.9")
          echo "Latest tag: $LATEST_TAG"

          if [[ $LATEST_TAG == v* ]]; then
            VERSION=${LATEST_TAG#v}
          else
            VERSION="1.0.0"
          fi

          IFS='.' read -r major minor patch <<< "$VERSION"
          if [ "$patch" -ge 9 ]; then
            patch=0
            if [ "$minor" -ge 9 ]; then
              minor=0
              major=$((major+1))
            else
              minor=$((minor+1))
            fi
          else
            patch=$((patch+1))
          fi

          NEW_VERSION="$major.$minor.$patch"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"

      - name: Create ZIP file
        run: |
          cd ${{ env.SOURCE_DIR }}
          zip -r ../${{ env.PLUGIN_NAME }}-${{ env.NEW_VERSION }}.zip .

      - name: Get recent commit messages since last release
        id: get_commits
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "no_tag")

          if [[ "$LATEST_TAG" == "no_tag" ]]; then
            COMMIT_MESSAGES="- Initial Release"
          else
            COMMIT_MESSAGES=$(git log $LATEST_TAG..HEAD --oneline | sed 's/^/- /')
          fi

          echo "COMMIT_MESSAGES<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MESSAGES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: v${{ env.NEW_VERSION }}
          body: |
            **Changes:**
            ${{ env.COMMIT_MESSAGES }}

            **How to download ⬇️**
            Click the file below named <code>${{ env.PLUGIN_NAME }}-${{ env.NEW_VERSION }}.zip</code> in the assets section to start the download automatically.

            **How to install 📦**
            Extract the compressed file and place the folder(s) in `${{ env.INSTALL_PATH }}`

            **Support me ❤️**
            Please consider leaving a ⭐ if it's helpful to your server.
          draft: false
          prerelease: false
          files: |
            ./${{ env.PLUGIN_NAME }}-${{ env.NEW_VERSION }}.zip